### ISSUE TITLE
Command fails when content of the record starts with a - (dash)

### ISSUE THREAD

**Issue by tbjornli** [mistial-dev/dns-challenge-cloudflare#3]
I ran into an issue where the command failed when the content of the record name starts with a - (dash).

I.e. 
```
$ /usr/local/sbin/dns-challenge setup domain.tld -OT31337Nfb9oUNZTH4cKErfJXPsSVsIKJmrTewFsJ

                                   
  The "-O" option does not exist.  
                                   

setup <zone> <challenge>
```

My workaround here was to add -- (double dash) to specify end of command options for the **MDChallengeDns01**

```
MDChallengeDns01 /usr/local/sbin/dns-challenge --
```

**Comment by kategray** [comment]
Thank you for your feedback.  I've updated the README to reflect your feedback.
